package org.lodsb.scales


/*
  +1>>  This source code is licensed as GPLv3 if not stated otherwise.
    >>  NO responsibility taken for ANY harm, damage done
    >>  to you, your data, animals, etc.
    >>
  +2>>
    >>  Last modified:  2013-11-07 :: 17:46
    >>  Origin: 
    >>
  +3>>
    >>  Copyright (c) 2013:
    >>
    >>     |             |     |
    >>     |    ,---.,---|,---.|---.
    >>     |    |   ||   |`---.|   |
    >>     `---'`---'`---'`---'`---'
    >>                    // Niklas Klügel
    >>
  +4>>
    >>  Made in Bavaria by fat little elves - since 1983.
 */


object ScaleLib {
  private lazy val ids2Names = generateEquivalenceClasses(12) ++ Map[Int, List[String]](
    (3926	->	List("Adonai Malakh (Israel)")),
    (2477	->	List("Aeolian Flat 1")),
    (2937	->	List("Algerian")),
    (3156	->	List("Altered Pentatonic")),
    (3456	->	List("Alternating Tetramirror")),
    (2772	->	List("Arezzo Major Diatonic Hexachord")),
    (2184	->	List("Augmented Chord")),
    (3248	->	List("Balinese Pentachord")),
    (3285	->	List("Bhairubahar Thaat (India)")),
    (2322	->	List("Bi Yu (China)")),
    (2418	->	List("Blues")),
    (3510	->	List("Blues Diminished")),
    (2964	->	List("Blues Dorian Hexatonic")),
    (3062	->	List("Blues Enneatonic")),
    (2422	->	List("Blues Heptatonic")),
    (2930	->	List("Blues Modified")),
    (2934	->	List("Blues Octatonic")),
    (3872	->	List("Blues Pentacluster")),
    (2386	->	List("Blues Pentatonic")),
    (3442	->	List("Blues Phrygian")),
    (2419	->	List("Blues With Leading Tone")),
    (2504	->	List("Center-Cluster Pentamirror")),
    (2896	->	List("Chad Gadyo (Israel)")),
    (2634	->	List("Chaio (China)")),
    (3799	->	List("Chromatic Bebop")),
    (4092	->	List("Chromatic Decamirror")),
    (3934	->	List("Chromatic Diatonic Dorian")),
    (3676	->	List("Chromatic Dorian")),
    (2515	->	List("Chromatic Dorian Inverse")),
    (4064	->	List("Chromatic Heptamirror")),
    (4032	->	List("Chromatic Hexamirror")),
    (2972	->	List("Chromatic Hypodorian")),
    (2510	->	List("Chromatic Hypodorian Inverse")),
    (3257	->	List("Chromatic Hypolydian")),
    (3305	->	List("Chromatic Hypolydian Inverse")),
    (3700	->	List("Chromatic Hypophrygian Inverse")),
    (3301	->	List("Chromatic Lydian")),
    (3385	->	List("Chromatic Lydian Inverse")),
    (3698	->	List("Chromatic Mixolydian")),
    (2675	->	List("Chromatic Mixolydian Inverse")),
    (4088	->	List("Chromatic Nonamirror")),
    (4080	->	List("Chromatic Octamirror")),
    (3968	->	List("Chromatic Pentamirror")),
    (3805	->	List("Chromatic Permuted Diatonic Dorian")),
    (2507	->	List("Chromatic Phrygian")),
    (3740	->	List("Chromatic Phrygian Inverse")),
    (3840	->	List("Chromatic Tetramirror")),
    (3584	->	List("Chromatic Trimirror")),
    (4094	->	List("Chromatic Undecamirror")),
    (2336	->	List("Diminished Chord")),
    (2925	->	List("Diminished Scale")),
    (2340	->	List("Diminished Seventh Chord")),
    (2775	->	List("Dominant Bebop")),
    (2706	->	List("Dominant Pentatonic")),
    (2902	->	List("Dorian")),
    (2910	->	List("Dorian Aeolian")),
    (2918	->	List("Dorian Flat 5")),
    (2836	->	List("Dorian Pentatonic")),
    (3392	->	List("Dorian Tetrachord")),
    (3290	->	List("Dorico Flamenco")),
    (3428	->	List("Double-Phrygian Hexatonic")),
    (2729	->	List("Eskimo Hexatonic 2 (North America)")),
    (2704	->	List("Eskimo Tetratonic (North America)")),
    (2911	->	List("Full Minor")),
    (3549	->	List("Genus Chromaticum")),
    (2805	->	List("Genus Diatonicum Veterum Correctum")),
    (2640	->	List("Genus Primum")),
    (2130	->	List("Genus Primum Inverse")),
    (2261	->	List("Genus Secundum")),
    (3292	->	List("Gipsy Hexatonic")),
    (2870	->	List("Gnossiennes")),
    (3449	->	List("Half-Diminished Bebop")),
    (2648	->	List("Han-kumoi (Japan)")),
    (2777	->	List("Harmonic Major")),
    (2905	->	List("Harmonic Minor")),
    (3286	->	List("Harmonic Minor Inverse")),
    (2848	->	List("Harmonic Minor Tetrachord")),
    (3929	->	List("Harmonic Neapolitan Minor")),
    (2837	->	List("Hawaiian")),
    (2840	->	List("Hira-joshi (Japan)")),
    (3426	->	List("Honchoshi Plagal Form (Japan)")),
    (3038	->	List("Houseini (Greece)")),
    (2517	->	List("Houzam (Greece)")),
    (2773 ->  List("Ionian")),
    (2486	->	List("Hungarian Major")),
    (2765	->	List("Ionian Sharp 5")),
    (3170	->	List("Iwato (Japan)")),
    (3376	->	List("Javanese Pentachord")),
    (2901	->	List("Jazz Minor")),
    (3414	->	List("Jazz Minor Inverse")),
    (2942	->	List("Kiourdi (Greece)")),
    (3154	->	List("Kokin-joshi, Miyakobushi (Japan)")),
    (2724	->	List("Kung (China)")),
    (3434	->	List("Locrian")),
    (2921	->	List("Locrian 2")),
    (3436	->	List("Locrian Double-Flat 7")),
    (3430	->	List("Locrian Natural 6")),
    (3424	->	List("Locrian Pentamirror")),
    (2741	->	List("Lydian")),
    (2733	->	List("Lydian Augmented")),
    (2869	->	List("Lydian Diminished")),
    (2709	->	List("Lydian Hexatonic")),
    (2746	->	List("Lydian Minor")),
    (2736	->	List("Lydian Pentachord")),
    (2485	->	List("Lydian Sharp 2")),
    (2453	->	List("Lydian Sharp 2 Hexatonic")),
    (3501	->	List("Magen Abot (Israel)")),
    (2773	->	List("Major")),
    (2781	->	List("Major Bebop")),
    (2716	->	List("Major Bebop Hexatonic")),
    (2192	->	List("Major Chord")),
    (3289	->	List("Major Gipsy")),
    (2794	->	List("Major Locrian")),
    (2778	->	List("Major Minor")),
    (3039	->	List("Major and Minor Mixed")),
    (2768	->	List("Major Pentachord")),
    (2708	->	List("Major Pentatonic")),
    (2049	->	List("Major Seventh Interval")),
    (2052	->	List("Major Sixth Interval")),
    (2752	->	List("Major Tetrachord")),
    (2176	->	List("Major Third Interval")),
    (3291	->	List("Maqam Hijaz (Arabia)")),
    (3558	->	List("Maqam Shadd'araban (Arabia)")),
    (3253	->	List("Marva Thaat (India)")),
    (3386	->	List("Mela Bhavapriya (India)")),
    (2739	->	List("Mela Citrambari (India)")),
    (2489	->	List("Mela Dhatuvardhani (India)")),
    (3260	->	List("Mela Dhavalambari (India)")),
    (3379	->	List("Mela Divyamani (India)")),
    (3673	->	List("Mela Ganamurti (India)")),
    (2521	->	List("Mela Gangeyabhusani (India)")),
    (3388	->	List("Mela Gavambodhi (India)")),
    (3283	->	List("Mela Hatakambari (India)")),
    (3642	->	List("Mela Jalarnava (India)")),
    (3641	->	List("Mela Jhalavarali (India)")),
    (2908	->	List("Mela Jhankaradhvani (India)")),
    (2490	->	List("Mela Jyotisvarupini (India)")),
    (2748	->	List("Mela Kantamani (India)")),
    (2745	->	List("Mela Latangi (India)")),
    (3669	->	List("Mela Manavati (India)")),
    (2780	->	List("Mela Mararanjani (India)")),
    (2771	->	List("Mela Naganandini (India)")),
    (3258	->	List("Mela Namanarayani (India)")),
    (3638	->	List("Mela Navanitam (India)")),
    (2867	->	List("Mela Nitimati (India)")),
    (3637	->	List("Mela Pavani (India)")),
    (2522	->	List("Mela Ragavardhani (India)")),
    (3635	->	List("Mela Raghupriya (India)")),
    (2483	->	List("Mela Rasikapriya (India)")),
    (3674	->	List("Mela Ratnangi (India)")),
    (3411	->	List("Mela Rupavati (India)")),
    (3382	->	List("Mela Sadvidhamargini (India)")),
    (3644	->	List("Mela Salaga (India)")),
    (2874	->	List("Mela Sanmukhapriya (India)")),
    (3420	->	List("Mela Senavati (India)")),
    (2492	->	List("Mela Sucaritra (India)")),
    (3381	->	List("Mela Suvarnangi (India)")),
    (2876	->	List("Mela Syamalangi (India)")),
    (3667	->	List("Mela Tanarupi (India)")),
    (3670	->	List("Mela Vanaspati (India)")),
    (2899	->	List("Mela Varunapriya (India)")),
    (3251	->	List("Mela Visvambhari (India)")),
    (2524	->	List("Mela Yagapriya (India)")),
    (3822	->	List("Messiaen Mode 3")),
    (3003	->	List("Messiaen Mode 3 Inverse")),
    (3900	->	List("Messiaen Mode 4")),
    (2535	->	List("Messiaen Mode 4 Inverse")),
    (3640	->	List("Messiaen Mode 5")),
    (2275	->	List("Messiaen Mode 5 Inverse")),
    (3770	->	List("Messiaen Mode 6")),
    (2795	->	List("Messiaen Mode 6 Inverse")),
    (4030	->	List("Messiaen Mode 7")),
    (3055	->	List("Messiaen Mode 7 Inverse")),
    (3380	->	List("Messiaen Truncated Mode 2")),
    (3276	->	List("Messiaen Truncated Mode 3")),
    (2457	->	List("Messiaen Truncated Mode 3 Inverse")),
    (3120	->	List("Messiaen Truncated Mode 5")),
    (2145	->	List("Messiaen Truncated Mode 5 Inverse")),
    (2600	->	List("Messiaen Truncated Mode 6")),
    (2210	->	List("Messiaen Truncated Mode 6 Inverse")),
    (2906	->	List("Minor","Aeolian")),
    (2388	->	List("Minor Added Sixth Pentatonic")),
    (3030	->	List("Minor Bebop")),
    (2966	->	List("Minor Bebop Hexatonic")),
    (2320	->	List("Minor Chord")),
    (2873	->	List("Minor Gipsy")),
    (2898	->	List("Minor Hexatonic")),
    (2922	->	List("Minor Locrian")),
    (3063	->	List("Minor Pentatonic With Leading Tones")),
    (2050	->	List("Minor Seventh Interval")),
    (2056	->	List("Minor Sixth Interval")),
    (2304	->	List("Minor Third Interval")),
    (2816	->	List("Minor Trichord")),
    (2774	->	List("Mixolydian")),
    (2790	->	List("Mixolydian Flat 5")),
    (2646	->	List("Mixolydian Hexatonic")),
    (2258	->	List("Mixolydian Pentatonic")),
    (2766	->	List("Mixolydian Sharp 5")),
    (3547	->	List("Moorish Phrygian")),
    (3413	->	List("Neapolitan Major")),
    (3417	->	List("Neapolitan Minor")),
    (3756	->	List("Neapolitan Minor Mode")),
    (3387	->	List("Neveseri (Greece)")),
    (2669	->	List("Nohkan (Japan)")),
    (3302	->	List("Oriental")),
    (3680	->	List("Oriental Pentacluster")),
    (2742	->	List("Overtone")),
    (3352	->	List("Pelog (Bali)")),
    (2064	->	List("Perfect Fifth Interval")),
    (2112	->	List("Perfect Forth Interval")),
    (3418	->	List("Phrygian")),
    (3930	->	List("Phrygian Aeolian")),
    (3482	->	List("Phrygian Flat 4")),
    (2394	->	List("Phrygian Hexatonic")),
    (3450	->	List("Phrygian Locrian")),
    (2880	->	List("Phrygian Tetrachord")),
    (3328	->	List("Phrygian Trichord")),
    (3435	->	List("Prokofiev Scale")),
    (2726	->	List("Prometheus")),
    (3238	->	List("Prometheus Neapolitan")),
    (2916	->	List("Pyramid Hexatonic")),
    (2884	->	List("Raga Abhogi (India)")),
    (2865	->	List("Raga Amarasenapriya (India)")),
    (2888	->	List("Raga Audav Tukhari (India)")),
    (2886	->	List("Raga Bagesri, Sriranjani, Kapijingla (India)")),
    (3225	->	List("Raga Bauli (India)")),
    (2514	->	List("Raga Bhanumanjari (India)")),
    (3317	->	List("Raga Bhatiyar (India)")),
    (2628	->	List("Raga Bhavani (India)")),
    (3370	->	List("Raga Bhavani (India)")),
    (2649	->	List("Raga Bhinna Pancama (India)")),
    (2245	->	List("Raga Bhinna Shadja, Hindolita (India)")),
    (2712	->	List("Raga Bhupeshwari, Janasammodini (India)")),
    (2180	->	List("Raga Bilwadala (India)")),
    (2737	->	List("Raga Caturangini (India)")),
    (3636	->	List("Raga Chandrajyoti (India)")),
    (2374	->	List("Raga Chandrakauns Kafi, Surya (India)")),
    (2377	->	List("Raga Chandrakauns Kiravani (India)")),
    (2373	->	List("Raga Chandrakauns Modern, Marga Hindola (India)")),
    (3368	->	List("Raga Chhaya Todi (India)")),
    (3400	->	List("Raga Chitthakarshini (India)")),
    (2878	->	List("Raga Cintamani (India)")),
    (3097	->	List("Raga Deshgaur (India)")),
    (2641	->	List("Raga Desh (India)")),
    (2137	->	List("Raga Devaranjani (India)")),
    (3256	->	List("Raga Dhavalangam (India)")),
    (2228	->	List("Raga Dhavalashri (India)")),
    (2800	->	List("Raga Dipak (India)")),
    (2257	->	List("Raga Gambhiranata (India)")),
    (3410	->	List("Raga Gandharavam (India)")),
    (3281	->	List("Raga Gaula (India)")),
    (3153	->	List("Raga Gauri (India)")),
    (2889	->	List("Raga Ghantana (India)")),
    (2630	->	List("Raga Guhamanohari (India)")),
    (3369	->	List("Raga Gurjari Todi (India)")),
    (2705	->	List("Raga Hamsadhvani (India)")),
    (3237	->	List("Raga Hamsanandi, Puriya (India)")),
    (2757	->	List("Raga Hamsa Vinodini (India)")),
    (2346	->	List("Raga Harikauns (India)")),
    (2632	->	List("Raga Haripriya (India)")),
    (3244	->	List("Raga Hejjajji (India)")),
    (2213	->	List("Raga Hindol (India)")),
    (3250	->	List("Raga Indupriya (India)")),
    (2618	->	List("Raga Jaganmohanam (India)")),
    (2402	->	List("Raga Jayakauns (India)")),
    (3157	->	List("Raga Jivantika (India)")),
    (2355	->	List("Raga Jivantini, Gaurikriya (India)")),
    (2234	->	List("Raga Jyoti (India)")),
    (3228	->	List("Raga Kalagada (India)")),
    (3164	->	List("Raga Kalakanthi (India)")),
    (3284	->	List("Raga Kalavati, Ragamalini (India)")),
    (2266	->	List("Raga Kamalamanohari (India)")),
    (3354	->	List("Raga Kashyapi (India)")),
    (2246	->	List("Raga Khamaji Durga (India)")),
    (2262	->	List("Raga Khamas, Baduhari (India)")),
    (2392	->	List("Raga Kokil Pancham (India)")),
    (3145	->	List("Raga Kshanika (India)")),
    (3593	->	List("Raga Kumarapriya (India)")),
    (2721	->	List("Raga Kumurdaki (India)")),
    (2134	->	List("Raga Kuntvarali (India)")),
    (2713	->	List("Raga Latika (India)")),
    (3144	->	List("Raga Lavangi (India)")),
    (2358	->	List("Raga Madhukauns (India)")),
    (2263	->	List("Raga Madhuri (India)")),
    (2194	->	List("Raga Mahathi (India)")),
    (3288	->	List("Raga Malahari (India)")),
    (2611	->	List("Raga Malarani (India)")),
    (2225	->	List("Raga Malashri (India)")),
    (3222	->	List("Raga Malayamarutam (India)")),
    (2378	->	List("Raga Malkauns (India)")),
    (2197	->	List("Raga Mamata (India)")),
    (3218	->	List("Raga Manaranjani (India)")),
    (2838	->	List("Raga Manavi (India)")),
    (3249	->	List("Raga Mandari, Gamakakriya (India)")),
    (2260	->	List("Raga Mand (India)")),
    (2390	->	List("Raga Manohari (India)")),
    (2582	->	List("Raga Matha Kokila (India)")),
    (3272	->	List("Raga Megharanjani (India)")),
    (3265	->	List("Raga Megharanji (India)")),
    (2643	->	List("Raga Megh (India)")),
    (2903	->	List("Raga Mian Ki Malhar, Bahar (India)")),
    (2452	->	List("Raga Mohanangi (India)")),
    (2725	->	List("Raga Mruganandana (India)")),
    (2353	->	List("Raga Multani (India)")),
    (3632	->	List("Raga Nabhomani (India)")),
    (2645	->	List("Raga Nagagandhari (India)")),
    (2769	->	List("Raga Nalinakanti, Kedaram (India)")),
    (2385	->	List("Raga Nata, Madhuranjani (India)")),
    (2650	->	List("Raga Navamanohari (India)")),
    (2860	->	List("Raga Neelangi (India)")),
    (2693	->	List("Raga Neroshta (India)")),
    (2209	->	List("Raga Nigamagamini (India)")),
    (2613	->	List("Raga Nishadi (India)")),
    (2096	->	List("Raga Ongkari (India)")),
    (3161	->	List("Raga Padi (India)")),
    (2783	->	List("Raga Pahadi (India)")),
    (2265	->	List("Raga Paraju, Simhavahini (India)")),
    (3162	->	List("Raga Phenadyuti (India)")),
    (2633	->	List("Raga Priyadharshini (India)")),
    (2133	->	List("Raga Puruhutika, Purvaholika (India)")),
    (3596	->	List("Raga Putrika (India)")),
    (2758	->	List("Raga Rageshri, Nattaikurinji (India)")),
    (2759	->	List("Raga Ragesri (India)")),
    (3031	->	List("Raga Ramdasi Malhar (India)")),
    (3321	->	List("Raga Ramkali (India)")),
    (2853	->	List("Raga Ranjani, Rangini (India)")),
    (2481	->	List("Raga Rasamanjari (India)")),
    (3158	->	List("Raga Rasavali (India)")),
    (2629	->	List("Raga Rasranjani (India)")),
    (3224	->	List("Raga Reva, Revagupti (India)")),
    (3270	->	List("Raga Rudra Pancama (India)")),
    (3346	->	List("Raga Rukmangi (India)")),
    (3350	->	List("Raga Salagavarali (India)")),
    (2354	->	List("Raga Samudhra Priya (India)")),
    (2761	->	List("Raga Sarasanana (India)")),
    (2614	->	List("Raga Sarasvati (India)")),
    (2268	->	List("Raga Saravati (India)")),
    (2128	->	List("Raga Sarvasri (India)")),
    (3128	->	List("Raga Saugandhini, Yashranjani (India)")),
    (3293	->	List("Raga Saurashtra (India)")),
    (2330	->	List("Raga Shailaja (India)")),
    (2612	->	List("Raga Shri Kalyan (India)")),
    (2597	->	List("Raga Shubravarni (India)")),
    (2866	->	List("Raga Simharava (India)")),
    (4059	->	List("Raga Sindhi Bhairavi (India)")),
    (2897	->	List("Raga Sindhura Kafi (India)")),
    (2770	->	List("Raga Siva Kambhoji, Vivardhini (India)")),
    (3273	->	List("Raga Sohini (India)")),
    (2647	->	List("Raga Sorati (India)")),
    (2900	->	List("Raga Suddha Bangala (India)")),
    (3660	->	List("Raga Suddha Mukhari (India)")),
    (3416	->	List("Raga Suddha Simantini (India)")),
    (2593	->	List("Raga Sumukam (India)")),
    (2872	->	List("Raga Syamalam (India)")),
    (2393	->	List("Raga Takka (India)")),
    (2259	->	List("Raga Tilang, Savitri (India)")),
    (2842	->	List("Raga Trimurti (India)")),
    (2609	->	List("Raga Vaijayanti (India)")),
    (2198	->	List("Raga Valaji (India)")),
    (3274	->	List("Raga Vasantabhairavi (India)")),
    (3269	->	List("Raga Vasanta, Chayavati (India)")),
    (2868	->	List("Raga Vijayanagari (India)")),
    (3633	->	List("Raga Vijayasri (India)")),
    (2227	->	List("Raga Vijayavasanta (India)")),
    (3401	->	List("Raga Viyogavarali (India)")),
    (2230	->	List("Raga Vutari (India)")),
    (2740	->	List("Raga Yamuna Kalyani (India)")),
    (2264	->	List("Raga Zilaf (India)")),
    (3402	->	List("Ritsu (Japan)")),
    (2518	->	List("Rock 'n' Roll")),
    (2249	->	List("Romanian Bacovia")),
    (3254	->	List("Romanian Major")),
    (2970	->	List("Sabach (Greece)")),
    (3160	->	List("Sakura Pentatonic (Japan)")),
    (2114	->	List("Sansagari (Japan)")),
    (2644	->	List("Scottish Pentatonic")),
    (3220	->	List("Scriabin")),
    (3072	->	List("Semitone Interval")),
    (3509	->	List("Shostakovich Scale")),
    (3562	->	List("Spanish Octatonic")),
    (3520	->	List("Spanish Pentacluster")),
    (3546	->	List("Spanish Phrygian")),
    (3498	->	List("Super Locrian")),
    (2642	->	List("Suspended Pentatonic")),
    (3835	->	List("Symmetrical Decatonic")),
    (2807	->	List("Taishikicho, Ryo (Japan)")),
    (2857	->	List("Takemitsu Tree Line Mode 1")),
    (2858	->	List("Takemitsu Tree Line Mode 2")),
    (2080	->	List("Tritone Interval")),
    (4095	->	List("Twelve-Tone Chromatic")),
    (3500	->	List("Ultra Locrian")),
    (2048	->	List("Unison")),
    (2306	->	List("Ute Tritonic (North America)")),
    (2907	->	List("Utility Minor")),
    (3307	->	List("Verdi Enigmatic")),
    (3243	->	List("Verdi Enigmatic Ascending")),
    (3275	->	List("Verdi Enigmatic Descending")),
    (2818	->	List("Warao Tetratonic (South America)")),
    (2560	->	List("Wholetone Interval")),
    (2730	->	List("Wholetone Scale")),
    (2731	->	List("Wholetone Scale With Leading Tone")),
    (2720	->	List("Wholetone Tetramirror")),
    (2688	->	List("Wholetone Trichord")),
    (3830	->	List("Youlan Scale (China)")),
    (2909	->	List("Zirafkend (Arabia)"))
  )

  //TODO: add G-System to generate all possible equivalence classes of scales up to X "chromatic" notes

  private val names2Ids = ids2Names.map({x =>
    x._2.map(l => (l, x._1))
  }).flatten.toMap

  val names = ids2Names.values.toList


  /**
   *  Find scale number given a name eg. "Algerian", "Dorian",...
   * @param name
   * @return
   */
  def id(name: String) = names2Ids.get(name)

  /**
   *  Looks up the name given a scale ID (number)
   * @param id
   * @return
   */

  def name(id: Int) = ids2Names.get(id)

  /**
   * Finds nearest scale to the given id (scale number)
   * @param id
   * @return
   */
  def findNearestId(id: Int) = {
    // crude
    var ret = 0
    var minDistance: Option[Int] = None

    ids2Names.foreach({
      tuple =>
        val currentId = tuple._1
        val distance = scala.math.abs(currentId - id)

        if ( minDistance == None || (distance < minDistance.get) ) {
          minDistance = Some(distance)
          ret = currentId
        }
    })

    ret
  }

  //TODO: Fixme, ScaleLib should use bigints here.. or not... may be too many classes for > 2^32
  /**
   * Generates all the unique equivalence classes in a scale with noBits number of pitches
   * @param noBits
   * @return Map -> scale ID (number) -> Class Name
   */
  def generateEquivalenceClasses(noBits: Int = 12) : Map[Int, List[String]] = {
    var map = Map[Int, List[String]]()

    val equivalenceClasses = BitSetOps.equivalenceClasses(noBits).zipWithIndex.map({
      x =>

        (x._1.toInt, List("Class "+x._2))
    })

    equivalenceClasses.foreach( x => map = map + x)

    map
  }
}
